### ISSUE TITLE
Register Username - Password in clear font

### ISSUE THREAD

**Issue by davidetaibi** [dteamswf/Serendipity#2]
When register a new user, the password is typed in clear fond and not hidden (see picture)

**Comment by davidetaibi** [comment]
![screenshot_2016-03-29-10-23-23](https://cloud.githubusercontent.com/assets/1090557/14102163/2e862a32-f599-11e5-8383-a59357f1819b.png)

**Comment by suomri** [comment]
This issue has been resolved in commit: 9c379ff77d701c6968db02a080ade78d2a84e6e7
