### ISSUE TITLE
Facebook Login is  not allowed

### ISSUE THREAD

**Issue by davidetaibi** [dteamswf/Serendipity#3]
Error: Application not configured: 

![screenshot_2016-03-29-10-22-46](https://cloud.githubusercontent.com/assets/1090557/14102184/45561948-f599-11e5-8621-8e9ddd05ac6b.png)

**Comment by rsuomela** [comment]
This issue has been resolved in commit: 9c379ff77d701c6968db02a080ade78d2a84e6e7

**Comment by suomri** [comment]
This issue will be resolved by generating a signed APK, with test mode disabled for the next release.

**Comment by suomri** [comment]
The Facebook login functionality can be enabled for all other users from the Facebook developer options once the application goes Live, public.
